# Setup
title:               Medieval Networks of Memory
tagline:             'A Text Technologies Project'
description:         'Medieval Networks of Memory is a digital project hosted by Stanford Text Technologies.'
url:                 https://medievalnetworks.github.io
baseurl:             '/mnm'
paginate:            5
permalink:           pretty


# About/contact
author:
  name:              Hannah Kim
  url:               
  email:             hkim24@stanford.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.9
google_analytics_id: #UA-XXXX-Y
